// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/service.proto
	pb/datadef.proto

It has these top-level messages:
	ContactReqResp
	Recipient
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ContactReqResp struct {
	Recipe       *Recipient `protobuf:"bytes,1,opt,name=recipe" json:"recipe,omitempty"`
	StateCode    int32      `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateMessage string     `protobuf:"bytes,3,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
}

func (m *ContactReqResp) Reset()                    { *m = ContactReqResp{} }
func (m *ContactReqResp) String() string            { return proto.CompactTextString(m) }
func (*ContactReqResp) ProtoMessage()               {}
func (*ContactReqResp) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{0} }

func (m *ContactReqResp) GetRecipe() *Recipient {
	if m != nil {
		return m.Recipe
	}
	return nil
}

func (m *ContactReqResp) GetStateCode() int32 {
	if m != nil {
		return m.StateCode
	}
	return 0
}

func (m *ContactReqResp) GetStateMessage() string {
	if m != nil {
		return m.StateMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*ContactReqResp)(nil), "pb.ContactReqResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SimpleGRpcService service

type SimpleGRpcServiceClient interface {
	CreateContact(ctx context.Context, in *ContactReqResp, opts ...grpc.CallOption) (*ContactReqResp, error)
	ReapContact(ctx context.Context, in *ContactReqResp, opts ...grpc.CallOption) (*ContactReqResp, error)
}

type simpleGRpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimpleGRpcServiceClient(cc *grpc.ClientConn) SimpleGRpcServiceClient {
	return &simpleGRpcServiceClient{cc}
}

func (c *simpleGRpcServiceClient) CreateContact(ctx context.Context, in *ContactReqResp, opts ...grpc.CallOption) (*ContactReqResp, error) {
	out := new(ContactReqResp)
	err := grpc.Invoke(ctx, "/pb.SimpleGRpcService/CreateContact", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleGRpcServiceClient) ReapContact(ctx context.Context, in *ContactReqResp, opts ...grpc.CallOption) (*ContactReqResp, error) {
	out := new(ContactReqResp)
	err := grpc.Invoke(ctx, "/pb.SimpleGRpcService/ReapContact", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SimpleGRpcService service

type SimpleGRpcServiceServer interface {
	CreateContact(context.Context, *ContactReqResp) (*ContactReqResp, error)
	ReapContact(context.Context, *ContactReqResp) (*ContactReqResp, error)
}

func RegisterSimpleGRpcServiceServer(s *grpc.Server, srv SimpleGRpcServiceServer) {
	s.RegisterService(&_SimpleGRpcService_serviceDesc, srv)
}

func _SimpleGRpcService_CreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleGRpcServiceServer).CreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SimpleGRpcService/CreateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleGRpcServiceServer).CreateContact(ctx, req.(*ContactReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleGRpcService_ReapContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleGRpcServiceServer).ReapContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SimpleGRpcService/ReapContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleGRpcServiceServer).ReapContact(ctx, req.(*ContactReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimpleGRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SimpleGRpcService",
	HandlerType: (*SimpleGRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContact",
			Handler:    _SimpleGRpcService_CreateContact_Handler,
		},
		{
			MethodName: "ReapContact",
			Handler:    _SimpleGRpcService_ReapContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}

func init() { proto.RegisterFile("pb/service.proto", fileDescriptorService) }

var fileDescriptorService = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0x49, 0xc5, 0x81, 0xc9, 0x58, 0x19, 0x1f, 0x08, 0xa5, 0x2a, 0x94, 0x8a, 0x50, 0x5c,
	0xb4, 0x38, 0xee, 0xdc, 0x76, 0xe1, 0x4a, 0x84, 0x8c, 0x7b, 0x49, 0xd3, 0x67, 0x09, 0xcc, 0x24,
	0xcf, 0x26, 0xcc, 0xc6, 0x9d, 0x57, 0xf0, 0x36, 0x5e, 0xc3, 0x2b, 0x78, 0x10, 0x69, 0xe2, 0x46,
	0x74, 0xe3, 0xf6, 0xfb, 0x93, 0x8f, 0xff, 0x7f, 0x7c, 0x49, 0x5d, 0xe3, 0x70, 0xdc, 0x69, 0x85,
	0x35, 0x8d, 0xd6, 0x5b, 0x48, 0xa8, 0xcb, 0x4f, 0x07, 0x6b, 0x87, 0x0d, 0x36, 0x92, 0x74, 0x23,
	0x8d, 0xb1, 0x5e, 0x7a, 0x6d, 0x8d, 0x8b, 0x2f, 0xf2, 0xe9, 0x4f, 0x2f, 0xbd, 0xec, 0xf1, 0x29,
	0x92, 0xf2, 0x85, 0x1f, 0xb6, 0xd6, 0x78, 0xa9, 0xbc, 0xc0, 0x67, 0x81, 0x8e, 0xe0, 0x82, 0xcf,
	0x46, 0x54, 0x9a, 0x30, 0x63, 0x05, 0xab, 0x16, 0xab, 0xb4, 0xa6, 0xae, 0x16, 0x13, 0xd1, 0x68,
	0xbc, 0xf8, 0x0e, 0xe1, 0x8c, 0x73, 0xe7, 0xa5, 0xc7, 0x47, 0x65, 0x7b, 0xcc, 0x92, 0x82, 0x55,
	0xfb, 0x62, 0x1e, 0x48, 0x6b, 0x7b, 0x84, 0x73, 0x9e, 0xc6, 0x78, 0x8b, 0xce, 0xc9, 0x01, 0xb3,
	0xbd, 0x82, 0x55, 0x73, 0x71, 0x10, 0xe0, 0x5d, 0x64, 0xab, 0x77, 0xc6, 0x8f, 0xd6, 0x7a, 0x4b,
	0x1b, 0xbc, 0x15, 0xa4, 0xd6, 0x71, 0x0c, 0x3c, 0xf0, 0xb4, 0x1d, 0x31, 0x88, 0x42, 0x31, 0x80,
	0xa9, 0xc1, 0xcf, 0x96, 0xf9, 0x1f, 0xac, 0x3c, 0x79, 0xfd, 0xf8, 0x7c, 0x4b, 0x8e, 0xcb, 0x65,
	0x58, 0xbf, 0xbb, 0x6a, 0x54, 0xcc, 0xdd, 0x0d, 0xbb, 0x84, 0x7b, 0xbe, 0x10, 0x28, 0xe9, 0xbf,
	0xce, 0x2c, 0x38, 0x01, 0x7e, 0x39, 0xbb, 0x59, 0x38, 0xe0, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x13, 0x62, 0x65, 0xce, 0x88, 0x01, 0x00, 0x00,
}
