// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/service.proto
	pb/data.proto

It has these top-level messages:
	LinkReqResp
	StatsReqResp
	Destination
	Link
	XLStats
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LinkReqResp struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace    string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Link         *Link  `protobuf:"bytes,4,opt,name=link" json:"link,omitempty"`
	StateCode    int32  `protobuf:"varint,5,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateMessage string `protobuf:"bytes,6,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
}

func (m *LinkReqResp) Reset()                    { *m = LinkReqResp{} }
func (m *LinkReqResp) String() string            { return proto.CompactTextString(m) }
func (*LinkReqResp) ProtoMessage()               {}
func (*LinkReqResp) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{0} }

func (m *LinkReqResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LinkReqResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LinkReqResp) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *LinkReqResp) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *LinkReqResp) GetStateCode() int32 {
	if m != nil {
		return m.StateCode
	}
	return 0
}

func (m *LinkReqResp) GetStateMessage() string {
	if m != nil {
		return m.StateMessage
	}
	return ""
}

type StatsReqResp struct {
	Xlstats      *XLStats `protobuf:"bytes,1,opt,name=xlstats" json:"xlstats,omitempty"`
	StateCode    int32    `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateMessage string   `protobuf:"bytes,3,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
}

func (m *StatsReqResp) Reset()                    { *m = StatsReqResp{} }
func (m *StatsReqResp) String() string            { return proto.CompactTextString(m) }
func (*StatsReqResp) ProtoMessage()               {}
func (*StatsReqResp) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{1} }

func (m *StatsReqResp) GetXlstats() *XLStats {
	if m != nil {
		return m.Xlstats
	}
	return nil
}

func (m *StatsReqResp) GetStateCode() int32 {
	if m != nil {
		return m.StateCode
	}
	return 0
}

func (m *StatsReqResp) GetStateMessage() string {
	if m != nil {
		return m.StateMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*LinkReqResp)(nil), "pb.LinkReqResp")
	proto.RegisterType((*StatsReqResp)(nil), "pb.StatsReqResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NpsWssService service

type NpsWssServiceClient interface {
	LinkStatsCreation(ctx context.Context, in *LinkReqResp, opts ...grpc.CallOption) (*LinkReqResp, error)
	NetFlowStats(ctx context.Context, in *StatsReqResp, opts ...grpc.CallOption) (*StatsReqResp, error)
}

type npsWssServiceClient struct {
	cc *grpc.ClientConn
}

func NewNpsWssServiceClient(cc *grpc.ClientConn) NpsWssServiceClient {
	return &npsWssServiceClient{cc}
}

func (c *npsWssServiceClient) LinkStatsCreation(ctx context.Context, in *LinkReqResp, opts ...grpc.CallOption) (*LinkReqResp, error) {
	out := new(LinkReqResp)
	err := grpc.Invoke(ctx, "/pb.NpsWssService/LinkStatsCreation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npsWssServiceClient) NetFlowStats(ctx context.Context, in *StatsReqResp, opts ...grpc.CallOption) (*StatsReqResp, error) {
	out := new(StatsReqResp)
	err := grpc.Invoke(ctx, "/pb.NpsWssService/NetFlowStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NpsWssService service

type NpsWssServiceServer interface {
	LinkStatsCreation(context.Context, *LinkReqResp) (*LinkReqResp, error)
	NetFlowStats(context.Context, *StatsReqResp) (*StatsReqResp, error)
}

func RegisterNpsWssServiceServer(s *grpc.Server, srv NpsWssServiceServer) {
	s.RegisterService(&_NpsWssService_serviceDesc, srv)
}

func _NpsWssService_LinkStatsCreation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpsWssServiceServer).LinkStatsCreation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NpsWssService/LinkStatsCreation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpsWssServiceServer).LinkStatsCreation(ctx, req.(*LinkReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpsWssService_NetFlowStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpsWssServiceServer).NetFlowStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NpsWssService/NetFlowStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpsWssServiceServer).NetFlowStats(ctx, req.(*StatsReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

var _NpsWssService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NpsWssService",
	HandlerType: (*NpsWssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LinkStatsCreation",
			Handler:    _NpsWssService_LinkStatsCreation_Handler,
		},
		{
			MethodName: "NetFlowStats",
			Handler:    _NpsWssService_NetFlowStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}

func init() { proto.RegisterFile("pb/service.proto", fileDescriptorService) }

var fileDescriptorService = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0xeb, 0x50,
	0x10, 0xc6, 0x49, 0xfa, 0xe7, 0xde, 0x4e, 0x9a, 0xdb, 0xde, 0x81, 0x0b, 0x21, 0xf4, 0x42, 0x89,
	0x08, 0xc5, 0x45, 0x83, 0x75, 0xe7, 0xb6, 0x20, 0x08, 0xb5, 0x42, 0xba, 0xd0, 0x9d, 0x9c, 0x34,
	0x43, 0x09, 0x4d, 0x73, 0x8e, 0x3d, 0x87, 0xaa, 0x5b, 0x5f, 0xc1, 0xc7, 0x70, 0xe5, 0xb3, 0xf8,
	0x0a, 0x3e, 0x88, 0x64, 0x0e, 0xad, 0xd2, 0x2e, 0x5c, 0x25, 0xf9, 0xcd, 0xe4, 0xfb, 0xe6, 0x9b,
	0x81, 0xae, 0x4a, 0x63, 0x4d, 0xeb, 0x4d, 0x3e, 0xa7, 0xa1, 0x5a, 0x4b, 0x23, 0xd1, 0x55, 0x69,
	0xd8, 0x5b, 0x48, 0xb9, 0x28, 0x28, 0x16, 0x2a, 0x8f, 0x45, 0x59, 0x4a, 0x23, 0x4c, 0x2e, 0x4b,
	0x6d, 0x3b, 0x42, 0x5f, 0xa5, 0x71, 0x26, 0x8c, 0xb0, 0x9f, 0xd1, 0x9b, 0x03, 0xde, 0x24, 0x2f,
	0x97, 0x09, 0xdd, 0x27, 0xa4, 0x15, 0xfe, 0x01, 0x37, 0xcf, 0x02, 0xa7, 0xef, 0x0c, 0x5a, 0x89,
	0x9b, 0x67, 0x88, 0x50, 0x2f, 0xc5, 0x8a, 0x02, 0x97, 0x09, 0xbf, 0x63, 0x0f, 0x5a, 0xd5, 0x53,
	0x2b, 0x31, 0xa7, 0xa0, 0xc6, 0x85, 0x2f, 0x80, 0x3d, 0xa8, 0x17, 0x79, 0xb9, 0x0c, 0xea, 0x7d,
	0x67, 0xe0, 0x8d, 0x7e, 0x0f, 0x55, 0x3a, 0x64, 0x03, 0xa6, 0xf8, 0x1f, 0x40, 0x1b, 0x61, 0xe8,
	0x6e, 0x2e, 0x33, 0x0a, 0x1a, 0x7d, 0x67, 0xd0, 0x48, 0x5a, 0x4c, 0xc6, 0x32, 0x23, 0x3c, 0x02,
	0xdf, 0x96, 0x57, 0xa4, 0xb5, 0x58, 0x50, 0xd0, 0x64, 0xf9, 0x36, 0xc3, 0x2b, 0xcb, 0xa2, 0x27,
	0x68, 0xcf, 0x8c, 0x30, 0x7a, 0x3b, 0xf3, 0x31, 0xfc, 0x7a, 0x2c, 0xaa, 0x0e, 0xcd, 0x83, 0x7b,
	0x23, 0xaf, 0x32, 0xbd, 0x9d, 0xd8, 0xa6, 0x6d, 0x6d, 0xcf, 0xda, 0xfd, 0xd1, 0xba, 0x76, 0x68,
	0x3d, 0x7a, 0x75, 0xc0, 0x9f, 0x2a, 0x7d, 0xa3, 0xf5, 0xcc, 0xee, 0x1d, 0xaf, 0xe1, 0x6f, 0x15,
	0x8f, 0xbd, 0xc6, 0x6b, 0xe2, 0x5d, 0x63, 0x67, 0x97, 0xda, 0x8e, 0x18, 0xee, 0x83, 0x28, 0x78,
	0x7e, 0xff, 0x78, 0x71, 0x31, 0xf2, 0xf9, 0x4c, 0x9b, 0xd3, 0xb8, 0xda, 0x8e, 0x3e, 0x77, 0x4e,
	0xf0, 0x12, 0xda, 0x53, 0x32, 0x17, 0x85, 0x7c, 0x60, 0x4d, 0xec, 0x56, 0xbf, 0x7e, 0xcf, 0x1b,
	0x1e, 0x90, 0xe8, 0x1f, 0xab, 0x75, 0x70, 0xa7, 0xc6, 0x89, 0xd3, 0x26, 0xdf, 0xf8, 0xec, 0x33,
	0x00, 0x00, 0xff, 0xff, 0x54, 0xf7, 0xb8, 0xa5, 0x28, 0x02, 0x00, 0x00,
}
