// Code generated by protoc-gen-gogo.
// source: pb/service.proto
// DO NOT EDIT!

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		pb/service.proto
		pb/demo.proto

	It has these top-level messages:
		DemoReqResp
		BootstrapReqResp
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CrdbService service

type CrdbServiceClient interface {
	Demo(ctx context.Context, in *DemoReqResp, opts ...grpc.CallOption) (*DemoReqResp, error)
	// Bootstrap an uninitialized cluster.
	InitCluster(ctx context.Context, in *BootstrapReqResp, opts ...grpc.CallOption) (*BootstrapReqResp, error)
}

type crdbServiceClient struct {
	cc *grpc.ClientConn
}

func NewCrdbServiceClient(cc *grpc.ClientConn) CrdbServiceClient {
	return &crdbServiceClient{cc}
}

func (c *crdbServiceClient) Demo(ctx context.Context, in *DemoReqResp, opts ...grpc.CallOption) (*DemoReqResp, error) {
	out := new(DemoReqResp)
	err := grpc.Invoke(ctx, "/pb.CrdbService/Demo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crdbServiceClient) InitCluster(ctx context.Context, in *BootstrapReqResp, opts ...grpc.CallOption) (*BootstrapReqResp, error) {
	out := new(BootstrapReqResp)
	err := grpc.Invoke(ctx, "/pb.CrdbService/InitCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CrdbService service

type CrdbServiceServer interface {
	Demo(context.Context, *DemoReqResp) (*DemoReqResp, error)
	// Bootstrap an uninitialized cluster.
	InitCluster(context.Context, *BootstrapReqResp) (*BootstrapReqResp, error)
}

func RegisterCrdbServiceServer(s *grpc.Server, srv CrdbServiceServer) {
	s.RegisterService(&_CrdbService_serviceDesc, srv)
}

func _CrdbService_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrdbServiceServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CrdbService/Demo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrdbServiceServer).Demo(ctx, req.(*DemoReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrdbService_InitCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapReqResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrdbServiceServer).InitCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CrdbService/InitCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrdbServiceServer).InitCluster(ctx, req.(*BootstrapReqResp))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrdbService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CrdbService",
	HandlerType: (*CrdbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Demo",
			Handler:    _CrdbService_Demo_Handler,
		},
		{
			MethodName: "InitCluster",
			Handler:    _CrdbService_InitCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}

func init() { proto.RegisterFile("pb/service.proto", fileDescriptorService) }

var fileDescriptorService = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0xd2, 0x2f,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x92, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb,
	0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x90, 0xe2, 0x2d, 0x48, 0xd2, 0x4f,
	0x49, 0xcd, 0xcd, 0x87, 0x70, 0x8d, 0x3a, 0x19, 0xb9, 0xb8, 0x9d, 0x8b, 0x52, 0x92, 0x82, 0x21,
	0xc6, 0x08, 0xd9, 0x72, 0xb1, 0xb8, 0xa4, 0xe6, 0xe6, 0x0b, 0xf1, 0xeb, 0x15, 0x24, 0xe9, 0x81,
	0x58, 0x41, 0xa9, 0x85, 0x41, 0xa9, 0xc5, 0x05, 0x52, 0xe8, 0x02, 0x4a, 0xc2, 0x4d, 0x97, 0x9f,
	0x4c, 0x66, 0xe2, 0x55, 0xe2, 0xd0, 0x2f, 0x33, 0x04, 0x9b, 0x68, 0xc5, 0xa8, 0x25, 0x64, 0xcd,
	0xc5, 0xed, 0x99, 0x97, 0x59, 0xe2, 0x9c, 0x53, 0x5a, 0x5c, 0x92, 0x5a, 0x24, 0x24, 0x02, 0xd2,
	0xe4, 0x94, 0x9f, 0x5f, 0x52, 0x5c, 0x52, 0x94, 0x58, 0x00, 0x33, 0x0a, 0xab, 0xa8, 0x12, 0x43,
	0x12, 0x1b, 0xd8, 0x49, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x9d, 0x1f, 0x50, 0xd7,
	0x00, 0x00, 0x00,
}
